### ISSUE TITLE
Map is blank (Chrome)

### ISSUE THREAD

**Issue by MennoSchepel** [maplabs/worldview#15]
Something broke?

index.524d94d9d5b53ed7ddbc.js:2 This page appears to be missing CSS declarations for Mapbox GL JS, which may cause the map to display incorrectly. Please ensure your page includes mapbox-gl.css, as described in https://www.mapbox.com/mapbox-gl-js/api/.
S @ index.524d94d9d5b53ed7ddbc.js:2
index.524d94d9d5b53ed7ddbc.js:2 Error: missing required property "version"
    at Object.Mn [as emitValidationErrors] (index.524d94d9d5b53ed7ddbc.js:2:347405)
    at Ue (index.524d94d9d5b53ed7ddbc.js:2:713234)
    at i._load (index.524d94d9d5b53ed7ddbc.js:2:715764)
    at index.524d94d9d5b53ed7ddbc.js:2:715389
    at index.524d94d9d5b53ed7ddbc.js:2:231517
Pt.fire @ index.524d94d9d5b53ed7ddbc.js:2
index.524d94d9d5b53ed7ddbc.js:2 Error: missing required property "sources"
    at Object.Mn [as emitValidationErrors] (index.524d94d9d5b53ed7ddbc.js:2:347405)
    at Ue (index.524d94d9d5b53ed7ddbc.js:2:713234)
    at i._load (index.524d94d9d5b53ed7ddbc.js:2:715764)
    at index.524d94d9d5b53ed7ddbc.js:2:715389
    at index.524d94d9d5b53ed7ddbc.js:2:231517
Pt.fire @ index.524d94d9d5b53ed7ddbc.js:2
index.524d94d9d5b53ed7ddbc.js:2 Error: missing required property "layers"
    at Object.Mn [as emitValidationErrors] (index.524d94d9d5b53ed7ddbc.js:2:347405)
    at Ue (index.524d94d9d5b53ed7ddbc.js:2:713234)
    at i._load (index.524d94d9d5b53ed7ddbc.js:2:715764)
    at index.524d94d9d5b53ed7ddbc.js:2:715389
    at index.524d94d9d5b53ed7ddbc.js:2:231517
Pt.fire @ index.524d94d9d5b53ed7ddbc.js:2

**Comment by hughesx5** [comment]
Hi,
The Worldview Chrome extension is no longer displaying a map, do you have advise on how to corrrect this.
Todate the extension has been removed and replaced
thanks

**Comment by rmumford** [comment]
Hi both, apologies for the interrupted service! 
We've submitted an update to the Google Chrome store today and it should be rolled out shortly. 
Thank you for you patience and for using Worldview!
